name:                monotonic-set-map
version:             0.1.0.0
github:              "michaeljklein/monotonic-set-map"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/monotonic-set-map#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- comonad
- containers >= 0.5.11.0
- criterion
- free

library:
  source-dirs: src

executables:
  monotonic-set-map-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monotonic-set-map

tests:
  monotonic-set-map-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monotonic-set-map
